import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";
import Jobs from "@/app/components/Jobs";
// import Here from "@/app/components/Here";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <main className="py-6 px-4 max-w-5xl mx-auto">
          <Header />
          {children}
          <footer className="py-8 text-gray-500">
            Job Bridge &copy; 2025 - All rights reservered
          </footer>
        </main>
      </body>
    </html>
  );
}
